### ISSUE TITLE
Errot: RequestVehicles Error to get data for Vehicles : 'Service unavailable. Please try later from www.bmw-connecteddrive.com'!"

### ISSUE THREAD

**Issue by thomasklein1975** [TA2k/ioBroker.bmw#1]
Hi,

I'm using your bmw-adapter (v2.0.0) but I did not get fresh data. in object "bmw.0._LetzerFehler" is the following value: "2021-08-07@14:31:06: "RequestVehicles Error to get data for Vehicles : 'Service unavailable. Please try later from www.bmw-connecteddrive.com'!""
The BMW-account is connected to a F11.

What can i do to solve issue?

Greetings
Thomas

**Comment by TA2k** [comment]
Please delete alle states under bmw.0. and restart the adapter

**Comment by thomasklein1975** [comment]
> Please delete alle states under bmw.0. and restart the adapter

no i got other errors in log:

![image](https://user-images.githubusercontent.com/47893316/128743912-fffc9cd4-8e27-4760-b003-ae18b7227c15.png)

**Comment by thomasklein1975** [comment]
here in plaint text: 
`{"error":"invalid_request","error_description":"The` request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed"}`

**Comment by TA2k** [comment]
Can you double check your passoword and login via app?

**Comment by thomasklein1975** [comment]
> Can you double check your passoword and login via app?

do i have to use app or would website be okay too? App is crashing atm

**Comment by TA2k** [comment]
Wait until the app is working again then the adapter is also working

**Comment by thomasklein1975** [comment]
thx, should it be App "My BMW" or "BMW connected"?

**Comment by TA2k** [comment]
MyBmw

**Comment by thomasklein1975** [comment]
now connection is done :-) 
But no any object about fuel any more? Many new with electric/charging
It is a BMW from 2016.
WIll Data like LastTrip will be filled soon?

Here are some errors left:

![image](https://user-images.githubusercontent.com/47893316/128759489-f8c6111b-99f4-4a32-a0fe-c598da78b052.png)

**Comment by raidsec** [comment]
same problem here.

**Comment by manny4566** [comment]
> 
> 
> now connection is done :-)
> But no any object about fuel any more? Many new with electric/charging
> It is a BMW from 2016.
> WIll Data like LastTrip will be filled soon?
> 
> Here are some errors left:
> 
> ![image](https://user-images.githubusercontent.com/47893316/128759489-f8c6111b-99f4-4a32-a0fe-c598da78b052.png)

Hi, i have the same problen.

**Comment by TA2k** [comment]
I need login credentials to check this contact me in the iobroker forum https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
please install via github to try the new v2 api

**Comment by thomasklein1975** [comment]
> 
> 
> please install via github to try the new v2 api

Hi,

I did update/install:

`$ iobroker url https://github.com/TA2k/ioBroker.bmw/tarball/master --host raspberrypi-iob

install TA2k/ioBroker.bmw#master

NPM version: 6.14.13

npm install TA2k/ioBroker.bmw#master --loglevel error --prefix "/opt/iobroker" (System call)

../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:

../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations] Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args); ^In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback( ^~~~~~~~~~~~../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations] Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args); ^

In file included from ../authenticate_pam.cc:23:../../nan/nan.h:1026:46: note: declared here NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback( ^~~~~~~~~~~~

../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:../authenticate_pam.cc:147:83: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’ Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked()); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,

from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate expects 2 arguments, 1 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’ V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate expects 2 arguments, 1 provided../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’ serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1); ^

In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’ int WriteUtf8(Isolate* isolate, char* buffer, int length = -1, ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:152:69: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’ res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked()); ^

In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate expects 2 arguments, 1 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’ V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate expects 2 arguments, 1 provided../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’ remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,

from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’ int WriteUtf8(Isolate* isolate, char* buffer, int length = -1, ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’ username->WriteUtf8(m->username, sizeof(m->username) - 1); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’ int WriteUtf8(Isolate* isolate, char* buffer, int length = -1, ^~~~~~~~~

/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’ password->WriteUtf8(m->password, sizeof(m->password) - 1); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’ int WriteUtf8(Isolate* isolate, char* buffer, int length = -1, ^~~~~~~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’../authenticate_pam.cc: At global scope:../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void void init(Handle<Object> exports) { ^~~~~~../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope

../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’ void init(Handle<Object> exports) { ^~~~~~ rand_r../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token void init(Handle<Object> exports) { ^../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope void init(Handle<Object> exports) { ^~~~~~~

In file included from ../../nan/nan.h:56, from ../authenticate_pam.cc:23:../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope NODE_MODULE(authenticate_pam, init); ^~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’ (node::addon_register_func) (regfunc), \ ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~

../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’ NODE_MODULE(authenticate_pam, init); ^~~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’ (node::addon_register_func) (regfunc), \ ^~~~~~~../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(authenticate_pam, init); ^~~~~~~~~~~

make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Error 1

gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack at ChildProcess.emit (events.js:376:20)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)gyp ERR! System Linux 5.10.17-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pamgyp ERR! node -v v14.17.0gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:

../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen); ^~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate); ^~~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose); ^~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush); ^~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:

../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet); ^~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet); ^~~~~~~~~~~~

../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’ results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts)); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’ results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr)); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’ results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd)); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate); ^~~~~~~~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’ results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate)); ^In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain); ^~~~~~~~~~~~~~

../src/serialport.cpp: At global scope:../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) { ^../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) { ^

In file included from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type] (node::addon_register_func) (regfunc), \ ^/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’ NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) ^~~~~~~~~~~~~../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~

make: *** [bindings.target.mk:112: Release/obj.target/bindings/src/serialport.o] Error 1

gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack at ChildProcess.emit (events.js:376:20)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

gyp ERR! System Linux 5.10.17-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.mysensors/node_modules/@serialport/bindingsgyp ERR! node -v v14.17.0gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

upload [4] bmw.admin /opt/iobroker/node_modules/iobroker.bmw/admin/words.js words.js application/javascript

upload [3] bmw.admin /opt/iobroker/node_modules/iobroker.bmw/admin/style.css style.css text/css

upload [2] bmw.admin /opt/iobroker/node_modules/iobroker.bmw/admin/index_m.html index_m.html text/html

upload [1] bmw.admin /opt/iobroker/node_modules/iobroker.bmw/admin/bmw.png bmw.png image/png

upload [0] bmw.admin /opt/iobroker/node_modules/iobroker.bmw/admin/admin.d.ts admin.d.ts video/mp2t

Update "system.adapter.bmw.0"

Process exited with code 0`


**Here are the logs:**

`bmw.0
2021-08-16 14:56:35.368	error	{"error":{"code":2012,"description":"(SmartPhoneUtil-A-2012) Resource not found. No status available for VIN WBA....."}}

bmw.0
2021-08-16 14:56:35.367	error	Error: Request failed with status code 404

bmw.0
2021-08-16 14:56:35.366	error	https://b2vapi.bmwgroup.com/webapi/v1/user/vehicles/WB...../status?deviceTime=2021-08-16T14:56:00&dlat=0&dlon=0

bmw.0
2021-08-16 14:56:28.490	info	starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.bmw, node: v14.17.0, js-controller: 3.3.15

bmw.0
2021-08-16 14:56:22.853	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

bmw.0
2021-08-16 14:56:22.852	info	terminating

bmw.0
2021-08-16 14:56:22.850	info	Got terminate signal TERMINATE_YOURSELF`

**Comment by TA2k** [comment]
With the latest version this should only appears at the start but you should have enough data about the car

**Comment by thomasklein1975** [comment]
> 
> 
> With the latest version this should only appears at the start but you should have enough data about the car

yes thx. data is been updated/filled but no info about fuel and last trips so far.

**Comment by TA2k** [comment]
contact me please via iobroker forum
https://forum.iobroker.net/user/tombox
