### ISSUE TITLE
How to use the remoteV2 order(s)

### ISSUE THREAD

**Issue by MSPtrs** [TA2k/ioBroker.bmw#10]
Dear developer,

I would like to use the remoteV2 order system in order to adjust the refresh interval and force a refresh via a blocky script.

It is described that the adress bmw.0.VIN.remotev2 is used for these orders but I don't have a clue how these orders which would be written to this adress have to look like.

Please apologise my probably unnessecary question but I really would like also be able to adjust the control rate of the adapter.

Best regards
MSPtrs

**Comment by TA2k** [comment]
bmw.0.xxxxxx.remotev2.force-refresh set true without ack
