### ISSUE TITLE
Automatic(?) translation of object ID to object Name

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [TA2k/ioBroker.bmw#15]
**Describe the bug**  
Possible error in automatic translation
bmw.0.WBAxxxxxxxxx.properties.vehicleLocation.heading is translated to 'Überschrift'.

**Expected behavior**  
Should be 'Richtung'

**Versions:**  
 - Adapter version: 2.5.1

**Comment by TA2k** [comment]
fixed
