### ISSUE TITLE
On month roll bmw.*.chargingSessions.YYYY-MM gets previous months sessions as well

### ISSUE THREAD

**Issue by j64bit** [TA2k/ioBroker.bmw#17]
**Describe the bug**  
In a new month the next directory in bmw.0.[VIN].chargingSessions.YYYY-MM gets created.
Unfortunately it then also contain the previous months data, which was copied over (so from MM-1).

Next steps then are all fine: New charging sessions get added correctly. The totals are correctly including the MM month, only.

**To Reproduce**  
Wait for a new month with charging sessions in current month

**Expected behavior**  
to not double/copy over the MM-1 data

**Screenshots & Logfiles**  
none

**Versions:**  
 - Adapter version: 2.5.3
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: raspiberry pi 64 bit

**Additional context**  
Its a great adapter - I can only recommend it.
Many thanks to all involved creating and maintaining it. Keep up the good work!

**Comment by TA2k** [comment]
should be fixed you can also fetch old month remotev2.fetch-charges
