### ISSUE TITLE
BMW seems to have changed the API again

### ISSUE THREAD

**Issue by FKuypers** [TA2k/ioBroker.bmw#18]
It seems like BMW has changed the API again, my log only shows the following:

```

bmw.0 | 2022-05-28 07:19:44.570 | error | Error: Request failed with status code 403
-- | -- | -- | --
bmw.0 | 2022-05-28 07:19:44.570 | error | getvehicles v2 failed

```
Other users of the API (for OpenWB) had to change the requester to version 2.5, since BMW just release this version for their app, maybe this is the problem here as well.

**Versions:**  
 - Adapter version: 2.51
 - JS-Controller version: 4.0.23
 - Node version: 14.19.0
 - Operating system: Ubuntu 20.4

**Comment by TA2k** [comment]
fixed with 2.5.4
