### ISSUE TITLE
Error: Request failed with status code 403 | getvehicles v2 failed

### ISSUE THREAD

**Issue by kkeintzel** [TA2k/ioBroker.bmw#19]
Since a couple of day, we get following error message:
![Bildschirmfoto 2022-05-28 um 09 23 43](https://user-images.githubusercontent.com/83504161/170815441-5c6b998a-0f69-4d66-abdc-6a028c0ca732.png)

iobroker "uptodate" with beta repository

![Bildschirmfoto 2022-05-28 um 09 32 01](https://user-images.githubusercontent.com/83504161/170815571-18a42c73-0ada-4ae4-add8-76c902814bd2.png)

**Comment by marl1329** [comment]
Nach einer kleinen Änderung im Adapter sind bei mir die Fehlermeldungen weg:
Alle Stellen im Adapter mit
"user-agent": "Dart/2.10 (dart:io)",
ändern in:
"user-agent": "Dart/2.14 (dart:io)",

und die Stellen mit
"x-user-agent": "android(v1.07_20200330);" + brand + ";1.5.2(8932)",
ändern in
"x-user-agent": "android(SP1A.210812.016.C1);" + brand + ";2.5.2(14945);row",
bzw. (je nachdem was wie die Zeile vorher aufgebaut war)
"x-user-agent": "android(SP1A.210812.016.C1);bmw;2.5.2(14945);row",

Gruß
Marl

**Comment by kkeintzel** [comment]
@marl1329 - Danke das hat gefruchtet !

**Comment by PortScanner** [comment]
Sorry, könntet ihr erklären, wie und wo diese Änderungen durchgeführt werden müssen.
Danke!

**Comment by kkeintzel** [comment]
stop bmw Instanz
o.a. Änderungen in
/opt/iobroker/node_modules/iobroker.bmw/main.js durchführen
start bmw  Instanz

**Comment by TA2k** [comment]
Mit 2.5.4 behoben

**Comment by MyhubMRa** [comment]
Fehler tritt seit vorgestern bei 2.5.4 auf, keine Änderung am System vorgenommen, lief zuvor stabil. 
Adapter grün, Remote Befehle funktionieren, aber kein Update der Datenpunkte. 
My BMW App läuft sauber.

**Comment by TA2k** [comment]
Mit 2.5.5 behoben

**Comment by Randy1st** [comment]
Sehr cool 
Vielen Dank!
