### ISSUE TITLE
Feature Request: Fetch Data on Request complementing longer Poll Cycles

### ISSUE THREAD

**Issue by tops4u** [TA2k/ioBroker.bmw#21]
**Describe the Request**  
In order to correctly calculate the needed Amount of Energy for the Wallbox i.e. to reach 80% Charge Level of a BEV we need to know the current SOC in the moment (or shortly after) Pluging in. With the current Polling-Mechanism this might take some time (Minutes). In order to have an accurate SOC. 

When setting the Polling Interval too short, the API will complain with Quota Exceeded and a possible long Wait-Time (that the current Adapter 2.5.5 does not handle well). 

**Proposed Solution**  
Still use the Polling Time but default it to a rather high default Time (5 Min +). 
Have a Trigger that might be triggered from JS / NodeRed in order to fetch current Data to represent actual Data (incl. SOC) for instance when charging starts. This might be as well used to trigger a Check if all Doors/Windows are closed when using Presence Check in the Home.

**Comment by tops4u** [comment]
Current Error (probably new from API): 
"**statusCode":403,"message":"Out of call volume quota. Quota will be replenished in 14:48:52."**

Actually it really means to wait for 14hours+!

**Comment by TA2k** [comment]
remote.force-refresh should do this

**Comment by tops4u** [comment]
Awesome. Thanks for the Super-Fast Answer. Sadly it was not known to me - I thought under remote are only functions available to the Mobile APP ie. lock doors etc... 

Maybe a short section on the readme would be helpfull.
