### ISSUE TITLE
Adapter does not update data. "Out of call volume quota"

### ISSUE THREAD

**Issue by guggu1** [TA2k/ioBroker.bmw#22]
**Describe the bug**  
The adapter does not retrieve data some time after the start. An error "Out of call volume quota" is logged, see attached log file. The log entry also specifies the time duration after which the the quota will be replenished. At this point in time, new data are retrieved for some time, until the quota is exceeded again.

**To Reproduce**  
the error occurs consistently.

**Screenshots & Logfiles**  
see attached logile.

**Versions:**  
 - Adapter version: 2.5.5
 - iobroker version: 3.3.22
 - JS-Controller version: 6.0.0
 - Node version: 18.9.0
 - Operating system:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Additional context**  
The adapter worked finde until a few days ago.
[iobroker.2022-09-21.log.pdf](https://github.com/TA2k/ioBroker.bmw/files/9619244/iobroker.2022-09-21.log.pdf)

**Comment by TA2k** [comment]
bmw reduces the daily quota. Please install via GitHub. wait for the quota limit. and try again with 5min interval

**Comment by guggu1** [comment]
I see that there is a new version, 2.5.6, which cannot be installed directly from iobroker. Do you mean to say I should install 2.5.6 viaa GitHub?

**Comment by TA2k** [comment]
yes

**Comment by guggu1** [comment]
It has worked. Consider it solved.

Thank you.

**Comment by TA2k** [comment]
Which interval is for you working?
