### ISSUE TITLE
v2.5.7 Klimastatus

### ISSUE THREAD

**Issue by Mephisto090** [TA2k/ioBroker.bmw#25]
Hej,

leider finde ich keine Informationen über die Klima. Läuft sie, Läuft sie nicht, usw.

Bin ich blind oder gibt es keine Informationen darüber? :D

VG

**Comment by vowill** [comment]
findet sich im Datenpunkt "climateControlState" mit INACTIVE oder HEATING oder VENTING (bei Fahrzeugen mit Verbrennungsmotor; ob Fahrzeuge mit e-Motor und e-Kompressor hier auch "CLIMATE" oder Ähnliches melden, ist mir nicht bekannt).
