### ISSUE TITLE
Wrong data type for status.fuelIndicators02.rangeValue field

### ISSUE THREAD

**Issue by JustJoe21** [TA2k/ioBroker.bmw#26]
The adapter shows in the log:

**State value to set for "bmw.0.XXXXXXXXXXXXXXXXX.status.fuelIndicators02.rangeValue" has to be type "number" but received type "string"**

 (the car is a PEV!)

Looks like the data type is not set correctly.

Adapter version: 2.5.7

**Comment by TA2k** [comment]
Mal den Datenpunkt löschen und adapter neustarten

**Comment by JustJoe21** [comment]
That did it! Thanks! :-)
