### ISSUE TITLE
ioBroker protokoll full with info 1 BMW found

### ISSUE THREAD

**Issue by oelison** [TA2k/ioBroker.bmw#27]
In the ioBroker protokoll every 5 minutes the following is printed:

bmw.0 | 2022-10-16 17:00:42.708 | info | Found 1 bmw vehicles

**To Reproduce**  
1. Activate the adapter :-)
2. go to the protocoll
3. more or less the most messages are from bmw.0

**Expected behavior**  
This info is not needed, only at restart or config change

**Versions:**  
 - Adapter version: 2.5.7
 - Node version: v16.17.0
 - Operating system: Linux

**Comment by TA2k** [comment]
The GitHub version has solved this

**Comment by oelison** [comment]
Thank you, great. I like this adapter. One remark: if you add #27 to the commit message, this is automaticly linked to the issue.
