### ISSUE TITLE
.properties.vehicleLocation.coordinates.latitude" has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by tipp88** [TA2k/ioBroker.bmw#29]
Wrong data type for vehicle location.

![image](https://user-images.githubusercontent.com/68737433/215981196-84f49f6d-2811-450b-a743-c78120a276aa.png)

**Comment by tipp88** [comment]
> bring es was die object zu löschen und den adapter neuzustarten

Ja, Fehler damit behoben. Danke!

**Comment by tipp88** [comment]
Muss das wieder öffnen. Jetzt kommt der Fehler wieder, nur umgekehrt...
properties.vehicleLocation.coordinates.latitude" has to be type "number" but received type "string"

**Comment by bahnuhr** [comment]
Ist bei mir auch so.
Auch das löschen der DP und Instanz neu starten bringt nix.
Es werden wieder "string" erstellt.
Bitte berichtigen.

**Comment by TA2k** [comment]
Bitte mal alle Objekte löschen
via github installieren und checken ob alle Objekte mit der richtigen Beschreibung erzeugt werden

**Comment by bahnuhr** [comment]
Objekte gelöscht
von git installiert.
Jetzt kommt im log:
bmw.0 | 2023-04-19 10:23:53.570 | error | TypeError: this.json2iob is not a function
bmw.0 | 2023-04-19 10:23:53.569 | error | getvehicles v2 failed

Die Instanz ist grün. Aber bei den Objekten kommt sehr wenig.
nur remotev2 und unter properties ist gar nichts drin.

**Comment by bahnuhr** [comment]
hab nochmal alles deinstalliert und dann wieder neu installiert.
Scheint nun zu funktionieren.

**Comment by TA2k** [comment]
wenn du zeit hast kannst du nochmal die git Version testen
