### ISSUE TITLE
Status Raw Json ? Wäre das möglich ?

### ISSUE THREAD

**Issue by wintermute11** [TA2k/ioBroker.bmw#30]
Ich habe Edomi im Einsatz und benutze deshalb iobroker zur Datensammlung, z.B. VWConnect. Hier übergebe ich ein Raw Json
an Edomi und werte das in Edomi aus. Nun ist noch ein Mini Cooper SE dazugekommen, den ich mit diesem super Adapter auch auslesen kann . Nur hier gibt es kein Raw Json, somit muss ich die Werte alle einzeln an Edomi übergeben, was sehr aufwändig und fehlerträchtig ist.
Wäre es möglich auch hier ein Raw Json für alle Werte zu implementieren ? Wäre eine tolle Sache !

**Comment by TA2k** [comment]
GitHub version hat state.rawJSON

**Comment by wintermute11** [comment]
Vielen Dank !
Perfekte Sache !
