### ISSUE TITLE
Login failed / Price model changed?

### ISSUE THREAD

**Issue by fah** [TA2k/ioBroker.bmw#31]
**Describe the bug**  
Log shows "Login failed" and according messages.

**To Reproduce**  
Start the plugin and wait. No further changes required to the former working setup.

**Expected behavior**  
Flawless login and api response.

**Screenshots & Logfiles**  
```log
bmw.0 |  2023-06-07 08:08:25.185 | error | undefined
bmw.0 | 2023-06-07 08:08:25.185 | error | Start relogin in 5min
bmw.0 | 2023-06-07 08:08:25.184 | error | Please check username and password or too many logins in 5 minutes
bmw.0 | 2023-06-07 08:08:25.184 | error | {"error":"invalid_client","error_description":"Client  authentication failed (e.g., login failure, unknown client, no client  authentication included or unsupported authentication method)"}
bmw.0 | 2023-06-07 08:08:25.184 | error | AxiosError: Request failed with status code 401
bmw.0 | 2023-06-07 08:08:25.183 | error | Login failed
```

**Versions:**  
 - Adapter version: 2.5.7
 - JS-Controller version: 4.0.24
 - Node version: v14.21.1
 - Operating system: Raspi

**Additional context**  
BMW mentions that the price model for the API "AOS" changes since May 23 ( https://bmw-cardata.bmwgroup.com/thirdparty/public/car-data/pricing ). Still the MyBMW App on iOS is running for free.

Settings:
Interval: 15 minutes intervals are set.
Brand: BMW

**Comment by prorun26** [comment]
the bmw api still works but BMW has new password conventions. try logging into the bmw website and changing the password. this will probably solve your problem

**Comment by fah** [comment]
I changed the password under https://www.bmw.de/de-de/mybmw/profile but still the same error message. Looks as if my account is locked. Please keep this open for a few days so I can contact BMW support and add feedback here.

**Comment by berndmr** [comment]
+1 here and watching if and how @fah can solve his problem.

**Comment by TA2k** [comment]
Bitte mal Passwort ändern und 1h nicht einloggen und adapter deaktivieren

**Comment by fah** [comment]
> Bitte mal Passwort ändern und 1h nicht einloggen und adapter deaktivieren

I did this multiple times already for 1-2 hours. Causing exactly the same error messages in log. 
Ticket has been opened at BMW helpdesk with link to this bug report. Waiting ...
Holiday season ...

**Comment by TA2k** [comment]
I don think they will react on the 3rd party resembled problem

**Comment by fah** [comment]
> I don think they will react on the 3rd party resembled problem

I asked why my API login is locked. The problem is on BMW's side.

**Comment by fah** [comment]
After trying again after a few days, it works again.
I did change the password, as mentioned above, in [https://www.bmw.de/de-de/mybmw/profile](https://www.bmw.de/de-de/mybmw/profile) 10 days ago. 
The old password was too simple. This caused maybe the misleading/wrong warning.
