### ISSUE TITLE
AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.bmw#33]
Bei mir klappt die V 2.6.0 nicht !

Properties fehlen.

Kommen diese noch ?

**Comment by kkickingereder** [comment]
Gleiches bei mi mit v.2.5.7

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
bmw.0 | 2023-07-01 08:41:07.263 | error | {"statusCode":404,"message":"Resource not found"}
bmw.0 | 2023-07-01 08:41:07.262 | error | AxiosError: Request failed with status code 404
bmw.0 | 2023-07-01 08:41:07.260 | error | getvehicles v2 failed




Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
bmw.0 | 2023-07-01 08:41:07.263 | error | {"statusCode":404,"message":"Resource not found"}
bmw.0 | 2023-07-01 08:41:07.262 | error | AxiosError: Request failed with status code 404
bmw.0 | 2023-07-01 08:41:07.260 | error | getvehicles v2 failed



Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
bmw.0 | 2023-07-01 08:41:07.263 | error | {"statusCode":404,"message":"Resource not found"}
bmw.0 | 2023-07-01 08:41:07.262 | error | AxiosError: Request failed with status code 404
bmw.0 | 2023-07-01 08:41:07.260 | error | getvehicles v2 failed

**Comment by bahnuhr** [comment]
2.5.7 geht nicht.
2.6.0 geht
Properties gibt es wohl nicht mehr.
Habe die DP woanders gefunden (wohl neu strukturiert).
