### ISSUE TITLE
Code 404 - getvehicles v2 failed

### ISSUE THREAD

**Issue by djtapedeck** [TA2k/ioBroker.bmw#34]
<html>
<body>

Since a some days the BMW vehicle data is not available anymore. Maybe BMW changed the API endpoints, so need to be adapted.
BMW App is working fine.

Below the error code in ioBorker.

{"statusCode":404,"message":"Resource not found"}
AxiosError: Request failed with status code 404
 getvehicles v2 failed

</body>
</html>

**Comment by vowill** [comment]
@djtapedeck: see closed issue https://github.com/TA2k/ioBroker.bmw/issues/32
