### ISSUE TITLE
'force-refresh" not working in V2.6.0

### ISSUE THREAD

**Issue by vowill** [TA2k/ioBroker.bmw#35]
In version 2.6.0, activating 'force-refresh' does not update the BMW data points any more.
According to the debug entry, 'force-refresh' only updates the entries in "mappingInfo" and in "attributes".
In contrast, the regular update driven by the adapter itself (via the time intervall set there) activates the entries in "state".
Would be great if that can be corrected.

**Comment by tipp88** [comment]
correct.

**Comment by TA2k** [comment]
fixed with 2.6.1

**Comment by vowill** [comment]
THANK YOU so much! Works fine now :-)
