### ISSUE TITLE
Abstürze wg. Uncaught Exception

### ISSUE THREAD

**Issue by DevChannel-de** [TA2k/ioBroker.bmw#36]
Hallo,
seit einigen Wochen bekomme ich solche Errors im Log:

bmw.0 | 2023-07-02 16:31:48.234 | info | terminating
-- | -- | -- | --
bmw.0 | 2023-07-02 16:31:47.731 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
bmw.0 | 2023-07-02 16:31:47.730 | info | terminating
bmw.0 | 2023-07-02 16:31:47.656 | error | Bad number
bmw.0 | 2023-07-02 16:31:47.655 | error | unhandled promise rejection: Bad number
bmw.0 | 2023-07-02 16:31:47.654 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bmw.0 | 2023-07-02 16:31:41.473 | info | Found 1 bmw vehicles
bmw.0 | 2023-07-02 16:31:40.766 | info | Start getting bmw vehicles
bmw.0 | 2023-07-02 16:31:39.980 | info | starting. Version 2.6.1 in /opt/iobroker/node_modules/iobroker.bmw, node: v16.20.0, js-controller: 5.0.5

Danach geht der Adapter auf Rot. 
Irgendeine Idee woran es liegen könnte?
ioBroker ist komplett aktualisiert.

**Comment by TA2k** [comment]
debug log an tombox2020@gmail.com wäre gut

**Comment by DevChannel-de** [comment]
Ich habe Linux neu aufsetzen müssen (dabei bin ich auch von Debian zu Ubuntu gegangen) und nach dem Neuaufsetzen von IoBroker tritt das Problem nicht mehr auf. Da der Fehler dadurch nicht mehr nachvollziehbar ist, werde ich dieses Issue jetzt auch schließen.
