### ISSUE TITLE
AxiosError: Request failed with status code 408

### ISSUE THREAD

**Issue by lessthanmore1** [TA2k/ioBroker.bmw#37]
bmw.0 | 2023-07-05 15:21:33.783 | error | {"statusCode":408,"message":"Request Timeout"}
bmw.0 | 2023-07-05 15:21:33.783 | error | AxiosError: Request failed with status code 408
bmw.0 | 2023-07-05 15:21:33.782 | error | update failed
bmw.0 | 2023-07-05 15:11:33.657 | error | {"statusCode":408,"message":"Request Timeout"}
bmw.0 | 2023-07-05 15:11:33.657 | error | AxiosError: Request failed with status code 408

Refresh steht auf 5 Minuten, Fehler kommt alle 10 Minuten.

**Comment by barznet** [comment]
+1

**Comment by bahnuhr** [comment]
Bei mir kommt der gleiche Fehler.

**Comment by prorun26** [comment]
+1

**Comment by TA2k** [comment]
Ich seh den Fehler nicht wann und wie oft kommt der

**Comment by barznet** [comment]
Bei mir sieht so aktuell aus

<img width="1339" alt="image" src="https://github.com/TA2k/ioBroker.bmw/assets/8721373/9d3efbf4-c944-4ce6-9050-5a61afe138a0">

Adapter bekommt gar keine Daten

<img width="1287" alt="image" src="https://github.com/TA2k/ioBroker.bmw/assets/8721373/7ac464ad-1f2d-4c9b-af69-40bb16b70105">

**Comment by prorun26** [comment]
![grafik](https://github.com/TA2k/ioBroker.bmw/assets/112396681/808859c0-364e-470c-b28e-4d1705a36e53)

**Comment by CenturyTTTT** [comment]
same error here as well

**Comment by Mabu54** [comment]
Bei mir kommt schon seit zwei Wochen der Fehler. Jetzt auch 404

bmw.0 | 2023-07-06 23:26:46.181 | error | {"statusCode":404,"message":"Resource not found"}
bmw.0 | 2023-07-06 23:26:46.181 | error | AxiosError: Request failed with status code 404
bmw.0 | 2023-07-06 23:26:46.180 | error | getvehicles v2 failed

**Comment by lessthanmore1** [comment]
> Bei mir kommt schon seit zwei Wochen der Fehler. Jetzt auch 404
> 
> bmw.0 | 2023-07-06 23:26:46.181 | error | {"statusCode":404,"message":"Resource not found"} bmw.0 | 2023-07-06 23:26:46.181 | error | AxiosError: Request failed with status code 404 bmw.0 | 2023-07-06 23:26:46.180 | error | getvehicles v2 failed

Das ist aber ein anderer Fehler. Aktualisiere am besten Mal den Adapter.

**Comment by CenturyTTTT** [comment]
ja seit heute gehts bei mir auch wieder. Allerdings fehlen die Properties wie bereits erwähnt.
