### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by lolax80** [TA2k/ioBroker.bmw#4]
**Describe the bug**  
In log there are request failed and there is no update of the objects. 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version
![Ohne Titel](https://user-images.githubusercontent.com/30566171/141073485-3dec0d28-f457-4f33-874c-fc94bf1833a3.jpg)

: <js-controller-version> 
node js v14.17.6
nem 6.14.15

**Comment by TA2k** [comment]
fixed

**Comment by lolax80** [comment]
The Problem is still there
