### ISSUE TITLE
ChargingState Path changed 

### ISSUE THREAD

**Issue by omc69** [TA2k/ioBroker.bmw#41]
**Describe the bug**  
VIN.properties.chargingState.chargePercentage seems to be obsolete and it's never gonna updated anymore . The new object and attributes are:

  "electricChargingState": {
            "chargingLevelPercent": 43,
            "chargingStatus": "NOT_CHARGING",
            "chargingTarget": 100,
            "isChargerConnected": true,
            "range": 215

I used bimmerconnected dumping the entire JSON Object from BMW's server.

Hope it helps !

Best,
Christian

**Comment by TA2k** [comment]
should be automatically under state

**Comment by omc69** [comment]
Issue seems to be fixed in 2.6.1 manually installed from github
