### ISSUE TITLE
Warnmeldung:  ...no existing object

### ISSUE THREAD

**Issue by Norb1204** [TA2k/ioBroker.bmw#47]
Hallo,
seit kurzem kommt in unregelmäßigen Abständen eine Warnmeldung:
![Warnung](https://github.com/TA2k/ioBroker.bmw/assets/132662785/9cff19cd-a136-4cc5-9c0d-7c0db02f27d8)

**Comment by TA2k** [comment]
auch mit 2.7.2 ?

**Comment by Norb1204** [comment]
ja, mit 2.7.2.
Meldung kommt nur sehr sporadisch, ich werde noch ein bisschen beobachten und Rückmeldung geben.

**Comment by manny4566** [comment]
Hi,

die Meldung kommt auch jedes Mal ca. 20 Sekunden nach dem Adapter Start. 

![grafik](https://github.com/TA2k/ioBroker.bmw/assets/23473485/f08c81c2-4001-499a-ad31-a3cbc6fd7430)

![grafik](https://github.com/TA2k/ioBroker.bmw/assets/23473485/67ef32e6-a49e-43e7-ac79-515306d62d8f)

Es scheint, dass der Adapter aus ~9,64€ -> ~9_64€ macht, also das Komma ihn stört.

**Comment by Norb1204** [comment]
Warnung kommt bei mir so ca. alle 6 Stunden

**Comment by TA2k** [comment]
Bitte mal die GitHub version testen ob da das auch noch passiert

**Comment by Norb1204** [comment]
Nach dem Neustart kamen schon mal keine Warnmeldungen, sieht mal gut aus, werde Morgen kurze Rückmeldung geben.
Super, Danke schon mal vorab

**Comment by Norb1204** [comment]
funktioniert bei mir, Danke

**Comment by Norb1204** [comment]
Bei mir kommen wieder Warnmeldungen.
<img width="1318" alt="image" src="https://github.com/TA2k/ioBroker.bmw/assets/132662785/6f89823f-c534-4ab1-a0f5-dcce9a9860ee">

**Comment by TA2k** [comment]
auch mit der GitHub version?

**Comment by Norb1204** [comment]
Ja, GitHub Version 2.7.2 ist installiert.
<img width="202" alt="image" src="https://github.com/TA2k/ioBroker.bmw/assets/132662785/81f90148-9612-4b92-ae93-39c281f4a2b7">

**Comment by TA2k** [comment]
heute installiert?

**Comment by Norb1204** [comment]
letzte Woche installiert.

**Comment by Norb1204** [comment]
In den Datenpunkten wird auch kein Wert angezeigt.
<img width="641" alt="image" src="https://github.com/TA2k/ioBroker.bmw/assets/132662785/8416221d-0e25-4c47-8836-c95105264205">

**Comment by Marc-Berg** [comment]
Bei mir auch noch, gerade von Github installiert. Es werden Objekte angelegt, bei denen aus meiner Sicht das eigentliche Value mit in der ObjectID und im Namen steht: `{
  "type": "state",
  "common": {
    "name": "~ 18,07 EUR",
    "role": "text",
    "type": "string",
    "write": false,
    "read": true
  },
  "native": {},
  "from": "system.adapter.bmw.0",
  "user": "system.user.admin",
  "ts": 1701284235849,
  "_id": "bmw.0.Wxxxxxxxx141.chargingSessions.2023-11.costsGroupedByCurrency.~ 18_07 EUR",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Norb1204** [comment]
Fehler ist bei mir weg seit dem letzten update.
Danke
