### ISSUE TITLE
Adapter Startprobleme

### ISSUE THREAD

**Issue by Norb1204** [TA2k/ioBroker.bmw#49]
Beim Neustart des Adapters ist dieser zwar grün, aktualisiert aber die Werte nicht. Nach einem erneuten Neustart des Adapters funktioniert es meistens.
Das ist ganz sporadisch, mal geht's,  mal auch nicht nach dem Neustart. Ich habe noch keinen Zusammenhang feststellen können.

Evtl. benötigt der Adapter nach einem Neustart eine positive Rückmeldung von BMW bevor dieser in die Aktualisierungsroutine übergeht?

**Comment by TA2k** [comment]
Nicht jeder Anfrage zu BMW ist erfolgreich gerade wenn zuviel anfrage durch ein Neustart gemacht werden. Einfach den Adapter laufen lassen

**Comment by Norb1204** [comment]
Adapter läuft mehrere Stunden ohne Aktualisierung. Nach einem Neustart geht es wieder. Habe das Phänomen schon mehrfach gehabt.

**Comment by TA2k** [comment]
dann debug log laufen lassen

**Comment by Norb1204** [comment]
melde mich wenn es wieder passiert

**Comment by Norb1204** [comment]
Erst mal frohe Weihnachten.

Wenn der Adapter gestartet wird und beim ersten Aufruf eine Fehlermeldung kommt (z.B. Request failed with status code 403), erfolgt kein weiterer Versuch, auch nach Stunden nicht.
![BMW Log](https://github.com/TA2k/ioBroker.bmw/assets/132662785/94745f04-071b-486e-96de-fde27b94007f)

**Comment by TA2k** [comment]
Ja habe ich schon in der GitHub version behoben

**Comment by Norb1204** [comment]
Funktioniert leider nicht.
Habe die GitHub Version nochmal installiert und getestet.
Sobald der Adapter gestartet wird und dann **direkt** eine Fehlermeldung im Log kommt ({"statusCode":403,"message":"Out of call volume quota ...), erfolgt kein weiterer zyklischer Aufruf. Der Adapter ist zwar grün aber es erfolgt keine Aktualisierung mehr. 

Wenn beim Start des Adapter die **Aktualisierung beim ersten Mal funktioniert**, geht alles, auch wenn später mal diese Fehlermeldung kommt.

Wie gesagt, das Phänomen kommt nur beim Start des Adapters wenn **direkt danach eine Fehlermeldung** kommt.

**Comment by TA2k** [comment]
Was sagt der Log denn genau eigentlich sollte ein Hinweis kommen

**Comment by Norb1204** [comment]
Nach der Fehlermeldung kommt kein Log-Eintrag mehr

**Comment by TA2k** [comment]
Bitte immer den exakten Log posten

**Comment by Norb1204** [comment]
Habe das ganze nochmals getestet inkl. log.
Nach der Fehlermeldung kommt ca. jede Stunde ein "refresh token" aber keine Aktualisierung.
[log.pdf](https://github.com/TA2k/ioBroker.bmw/files/13780148/log.pdf)

**Comment by TA2k** [comment]
die GitHub version sollte jetzt korrekt auf die situation reagieren

**Comment by Norb1204** [comment]
funktioniert.
super, Danke
