### ISSUE TITLE
Datapoints missing (charging level, kilometer, reach)

### ISSUE THREAD

**Issue by HochdruckHummer** [TA2k/ioBroker.bmw#54]
Installed version 2.8.0 after trying all the stable build with no success.
Added my login credentials, connection to BMW established, but it seems not all data points are visible, that should be visible. 
For example there is no charge level, total kilometers, reach.

![image](https://github.com/TA2k/ioBroker.bmw/assets/60255369/20180808-3880-4b7f-a74e-ea19283900fa)

I've tried and installed the adapter a few more times, and  but I can't get it to work. Also I tried adding another instance, without success. Data is still missing.

 Is there any way to do this? Is this a known error? Can this be caused by quota limitations as well?

**Comment by TA2k** [comment]
which information are under state?

**Comment by JaroniStefan** [comment]
@HochdruckHummer Might depend on your car. I have a 2015 520d with NBT system. This doesn't support what they call LSC (Last State Call). As I understand it information like kilometer/mileage is send to the ConnectedDrive servers through that LSC. So if the car doesn't support transmission to the ConnectedDrive server you'll have no data in ioBroker either. As I recall they stopped some of the services when 3G was taken offline in Germany. The "old" cars only supported up to 3G and use 2G now :-(
