### ISSUE TITLE
I get no objects, even adapter works fine and status is "green"

### ISSUE THREAD

**Issue by AxelG-DE** [TA2k/ioBroker.bmw#64]
**Describe the bug**  
There is almost nothing in the objects
The only thing I get is the "INFO" object

**To Reproduce**  
1. Go to Objects
2. See error

**Expected behavior**  
Objects as intended should appear

**Screenshots & Logfiles**  

![grafik](https://github.com/user-attachments/assets/7a74f455-9674-4132-ad44-6e4aa2e57554)

```
bmw.0 	2024-09-24 21:23:26.453	error	{"statusCode":404,"message":"Resource not found"}
bmw.0 	2024-09-24 21:23:26.452	error	AxiosError: Request failed with status code 404
bmw.0 	2024-09-24 21:23:26.451	error	getvehicles v2 failed
bmw.0 	2024-09-24 21:23:26.361	info	Start getting bmw vehicles
bmw.0 	2024-09-24 21:23:25.615	info	starting. Version 2.5.7 in /opt/iobroker/node_modules/iobroker.bmw, node: v18.20.4, js-controller: 6.0.11
bmw.0 	2024-09-24 21:23:18.604	info	terminating
bmw.0 	2024-09-24 21:23:18.103	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
bmw.0 	2024-09-24 21:23:18.101	info	terminating
bmw.0 	2024-09-24 21:23:18.099	info	Got terminate signal TERMINATE_YOURSELF
```

**Versions:**  
 - Adapter version: 2.5.7 (just now re-installed due to no avail)
 - JS-Controller version: 6.0.11
 - Node version: v18.20.4
 - Operating system: raspian OS 12.7

**Additional context**

**Comment by AxelG-DE** [comment]
BTW: I do have fine access via BMW myAPP (2 vehicles)

**Comment by TA2k** [comment]
please use v2.8.0

**Comment by AxelG-DE** [comment]
Sorry beeing so boon, I did switch to beta repository but that didn't give me the 2.8 
I remember, I may need to do something about npm installation? Seems I gotta google-y a bit  :-P

**Comment by AxelG-DE** [comment]
o.k., hat gave me this: https://www.npmjs.com/package/iobroker.bmw/v/1.0.0

and from here I ended up there: 

$ npm i iobroker.bmw@1.0.0
```

added 3 packages, removed 41 packages, changed 1 package, and audited 5 packages in 3s

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
iob@iobroker:~ $ npm audit
# npm audit report

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
fix available via `npm audit fix`
node_modules/xml2js
  iobroker.bmw  1.0.0
  Depends on vulnerable versions of xml2js
  node_modules/iobroker.bmw

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix
```
Not that simple for a normal user :-/ even it might be written everything there but chugging the consequences...

**Comment by AxelG-DE** [comment]
That was a ride...
Finally I did it according to this and it worked: https://www.youtube.com/watch?v=Sgj_80GCZxE
