### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.bmw#65]
Hallo, Fehler im log:
`<html>
<body>

bmw.0 | 2024-09-30 09:19:45.310 | error | {"statusCode":404,"message":"Resource not found"}
-- | -- | -- | --
bmw.0 | 2024-09-30 09:19:45.310 | error | AxiosError: Request failed with status code 404
bmw.0 | 2024-09-30 09:19:45.310 | error | Remote command failed

</body>
</html>`

vgl. auch:
https://forum.iobroker.net/topic/46720/test-adapter-bmw-mini-v2-0-0/592?page=30

Da wird irgendwas nicht gefunden.

**Comment by Ralf-Niemeier** [comment]
Same here

**Comment by TA2k** [comment]
2.8.1 testen

**Comment by Ralf-Niemeier** [comment]
2.8.1 Funktioniert bei mir (wieder) 
*freu*

**Comment by bahnuhr** [comment]
@TA2k 
Was war das Problem?
Würde mich interessieren.

**Comment by TA2k** [comment]
api url hat sich geändert
