### ISSUE TITLE
Feature Request - Fahrzeuge selektieren bzw. Fahrzeuge abwählen/ignorieren  

### ISSUE THREAD

**Issue by prorun26** [TA2k/ioBroker.bmw#66]
Mit meinem BMW-Account sind mehrere Fahrzeuge verknüpft. Ich möchte jedoch nur ein bestimmtes Fahrzeug abfragen. Eine Möglichkeit Fahrzeuge abzuwählen oder ignorieren zu können wäre klasse. 

Vermutlich könnte so auch das Traffic-Problem zum BMW-Server minimiert werden:

```
{"statusCode":403,"message":"Out of call volume quota. Quota will be replenished in 00:25:20."}
AxiosError: Request failed with status code 403
getvehicles v2 failed
```

**Comment by TA2k** [comment]
bitte GitHub version testen

**Comment by prorun26** [comment]
Die neue "VIN Ignore List" funktioniert einwandfrei. Mehrere VINs können mit einem Komma getrennt eigetragen werden. 
Ich beobachte noch ob alle States weiterhin fehlerfrei ankommen und gebe dann noch mal ein Feedback.

Vielen Dank schon mal für die extrem schnelle Umsetzung - Daumen hoch!!

**Comment by prorun26** [comment]
Sieht gut aus. Bei mir funktioniert alles fehlerfrei.
