### ISSUE TITLE
getvehicles v2 failed

### ISSUE THREAD

**Issue by Ralf-Niemeier** [TA2k/ioBroker.bmw#68]
After the Update to the Version 2.8.1 the Adapter works verry well.

Now i got a new error in the log:

_bmw.0	2024-10-05 18:16:21.838	info	Adapter will retry in 3 minutes to get vehicles
bmw.0	2024-10-05 18:16:21.838	error	TypeError: Cannot read properties of undefined (reading 'replace')
bmw.0	2024-10-05 18:16:21.838	error	getvehicles v2 failed
bmw.0	2024-10-05 18:16:21.838	info	Found 1 bmw vehicles
bmw.0	2024-10-05 18:16:21.519	info	Start getting bmw vehicles_

What can i do ?

**Comment by TA2k** [comment]
update to 2.8.2

**Comment by Ralf-Niemeier** [comment]
Version 2.8.2

Fine :-)

No erros at all.

Tx a lot !

**Comment by Ralf-Niemeier** [comment]
Sorry, but after restart the adapter a second time, the same error is back :-(

<html>
<body>

bmw.0 | 2024-10-06 20:49:27.222 | info | Adapter will retry in 3 minutes to get vehicles
-- | -- | -- | --
bmw.0 | 2024-10-06 20:49:27.222 | warn | Rate Limit exceeded, please wait 5 minutes
bmw.0 | 2024-10-06 20:49:27.221 | error | {"statusCode":403,"message":"Out of call volume quota. Quota will be replenished in 00:10:33."}
bmw.0 | 2024-10-06 20:49:27.221 | error | AxiosError: Request failed with status code 403
bmw.0 | 2024-10-06 20:49:27.221 | error | getvehicles v2 failed
bmw.0 | 2024-10-06 20:49:27.087 | info | Start getting bmw vehicles
bmw.0 | 2024-10-06 20:49:26.466 | info | starting. Version 2.8.2 (non-npm: TA2k/ioBroker.bmw) in /opt/iobroker/node_modules/iobroker.bmw, node: v18.18.0, js-controller: 6.0.11


</body>
</html>

**Comment by Ralf-Niemeier** [comment]
Clean log:

_bmw.0	2024-10-06 20:49:27.222	info	Adapter will retry in 3 minutes to get vehicles
bmw.0	2024-10-06 20:49:27.222	warn	Rate Limit exceeded, please wait 5 minutes
bmw.0	2024-10-06 20:49:27.221	error	{"statusCode":403,"message":"Out of call volume quota. Quota will be replenished in 00:10:33."}
bmw.0	2024-10-06 20:49:27.221	error	AxiosError: Request failed with status code 403
bmw.0	2024-10-06 20:49:27.221	error	getvehicles v2 failed
bmw.0	2024-10-06 20:49:27.087	info	Start getting bmw vehicles
bmw.0	2024-10-06 20:49:26.466	info	starting. Version 2.8.2 (non-npm: TA2k/ioBroker.bmw) in /opt/iobroker/node_modules/iobroker.bmw, node: v18.18.0, js-controller: 6.0.11_

**Comment by Ralf-Niemeier** [comment]
I'll test it in the next week carefully!

**Comment by cadkiwi** [comment]
Same issue here with 2.8.2

**Comment by Ralf-Niemeier** [comment]
I have no issus any more.

Thx.
