### ISSUE TITLE
v2.4.1 does not connect to BMW backend

### ISSUE THREAD

**Issue by git-kick** [TA2k/ioBroker.bmw#8]
**Describe the bug**  
v2.4.1 does not connect to BMW backend

**To Reproduce**  
1. Install v2.4.1
2. Create instance, enter e-mail & password
3. look at ioBroker log

**Expected behavior**  
Adapter should connect to BMW backend

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/8932938/142260389-8475cc4d-bb4c-4a57-8ce5-2ed09d78507d.png)

**Versions:**  
 - Adapter version: 2.4.1
 - JS-Controller version: 5.2.13
 - Node version: 4.15.3
 - Operating system: Win 11

**Additional context**

**Comment by TA2k** [comment]
Mit 2.5.0 behoben

**Comment by andig** [comment]
@TA2k you can skip the entire part in https://github.com/TA2k/ioBroker.bmw/commit/051cbafa9b867e94a49dba9fac2ce170c09b6abb if you just use `token` response type

**Comment by TA2k** [comment]
This is correct but this is not how the App is behaving and very likely it will blocked in future.
