### ISSUE TITLE
Error while starting the bmw instance

### ISSUE THREAD

**Issue by kkeintzel** [TA2k/ioBroker.bmw#9]
Error: Request failed with status code 400
--

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed"}
--
![Bildschirmfoto 2021-11-17 um 20 06 03](https://user-images.githubusercontent.com/83504161/142266239-9f8a415b-e1cf-4f59-8af0-aa202fb29145.png)

![Bildschirmfoto 2021-11-17 um 20 07 25](https://user-images.githubusercontent.com/83504161/142266315-9847b554-a5d5-4519-a88d-72e8d20d2adb.png)

**Comment by gBonfire** [comment]
Hallo,
hatte das gleiche Problem. Sämtliche Versuche dies zu beheben (Adapter deinstallieren, Objekte und Instanzen löschen, aus unterschiedlichen Quellen installieren etc.) brachten keine Besserung.
Lösung war: 
iobroker stop
iobroker backup
Verzeichnisse von NodeRed sichern.
Iobroker neu installieren
iobroker restore
Verzeichnisse von NodeRed wieder zurücksichern.
Funktioniert.

Nur als Hinweis, was bei mir funktionierte. 
Soll nicht heissen, dass du das auch so machen musst. Will nur meine Erkenntnisse mit dir und weiteren geneigten Lesern teilen.
Die eigentliche Ursache konnte nicht ermittelt werden. War aber auch schon eine uralte Installation auf die immer wieder aufgebaut wurde.
Jetzt habe ich ne frische Installation, die sogar performanter läuft. Datenverlust hatte ich durch die oben zusammengefasste Vorgehensweise nicht.
Zeitaufwand (Laufzeiten, viele Adapter, viel VIs) ca. 2 Stunden. Davon ca. 5 Minuten "arbeitszeit", der Rest war warten, bis alle Adapter heruntergeladen und die Instanzen erzeugt waren.

Viel Erfolg!

**Comment by TA2k** [comment]
Mit 2.5.0 behoben
